insert into accountability (accountability_id, state, city, collected, processed, unprocessed) values (1, 'MD', 'Ridgely', 252, 174, 330);
insert into accountability (accountability_id, state, city, collected, processed, unprocessed) values (2, 'SC', 'Columbia', 339, 148, 466);
insert into accountability (accountability_id, state, city, collected, processed, unprocessed) values (3, 'NC', 'Raleigh', 300, 489, 434);
insert into accountability (accountability_id, state, city, collected, processed, unprocessed) values (4, 'KS', 'Wichita', 57, 320, 314);
insert into accountability (accountability_id, state, city, collected, processed, unprocessed) values (5, 'CO', 'Denver', 104, 14, 25);
insert into accountability (accountability_id, state, city, collected, processed, unprocessed) values (6, 'PA', 'Philadelphia', 82, 122, 299);
insert into accountability (accountability_id, state, city, collected, processed, unprocessed) values (7, 'TX', 'Lubbock', 406, 497, 291);
insert into accountability (accountability_id, state, city, collected, processed, unprocessed) values (8, 'TX', 'Spring', 123, 150, 310);
insert into accountability (accountability_id, state, city, collected, processed, unprocessed) values (9, 'OH', 'Cincinnati', 404, 95, 376);
insert into accountability (accountability_id, state, city, collected, processed, unprocessed) values (10, 'TX', 'San Antonio', 375, 167, 148);
insert into accountability (accountability_id, state, city, collected, processed, unprocessed) values (11, 'CO', 'Colorado Springs', 443, 479, 428);
insert into accountability (accountability_id, state, city, collected, processed, unprocessed) values (12, 'MO', 'Saint Louis', 327, 358, 293);
insert into accountability (accountability_id, state, city, collected, processed, unprocessed) values (13, 'CA', 'Sacramento', 53, 161, 111);
insert into accountability (accountability_id, state, city, collected, processed, unprocessed) values (14, 'TX', 'Austin', 480, 159, 396);
insert into accountability (accountability_id, state, city, collected, processed, unprocessed) values (15, 'WV', 'Huntington', 150, 120, 69);
insert into accountability (accountability_id, state, city, collected, processed, unprocessed) values (16, 'DC', 'Washington', 323, 173, 417);
insert into accountability (accountability_id, state, city, collected, processed, unprocessed) values (17, 'IL', 'Chicago', 205, 427, 113);
insert into accountability (accountability_id, state, city, collected, processed, unprocessed) values (18, 'CA', 'Santa Barbara', 357, 279, 279);
insert into accountability (accountability_id, state, city, collected, processed, unprocessed) values (19, 'OH', 'Cincinnati', 333, 233, 187);
insert into accountability (accountability_id, state, city, collected, processed, unprocessed) values (20, 'TX', 'Houston', 326, 58, 115);
insert into accountability (accountability_id, state, city, collected, processed, unprocessed) values (21, 'CO', 'Denver', 237, 108, 374);
insert into accountability (accountability_id, state, city, collected, processed, unprocessed) values (22, 'MS', 'Gulfport', 47, 16, 335);
insert into accountability (accountability_id, state, city, collected, processed, unprocessed) values (23, 'TX', 'Houston', 2, 204, 115);
insert into accountability (accountability_id, state, city, collected, processed, unprocessed) values (24, 'GA', 'Decatur', 260, 448, 258);
insert into accountability (accountability_id, state, city, collected, processed, unprocessed) values (25, 'TX', 'Austin', 206, 155, 303);
insert into accountability (accountability_id, state, city, collected, processed, unprocessed) values (26, 'FL', 'Orlando', 275, 183, 228);
insert into accountability (accountability_id, state, city, collected, processed, unprocessed) values (27, 'OK', 'Tulsa', 415, 127, 387);
insert into accountability (accountability_id, state, city, collected, processed, unprocessed) values (28, 'OH', 'Warren', 104, 220, 467);
insert into accountability (accountability_id, state, city, collected, processed, unprocessed) values (29, 'FL', 'Saint Petersburg', 28, 330, 492);
insert into accountability (accountability_id, state, city, collected, processed, unprocessed) values (30, 'FL', 'Pensacola', 387, 273, 347);
insert into accountability (accountability_id, state, city, collected, processed, unprocessed) values (31, 'GA', 'Atlanta', 284, 107, 399);
insert into accountability (accountability_id, state, city, collected, processed, unprocessed) values (32, 'TX', 'El Paso', 345, 365, 120);
insert into accountability (accountability_id, state, city, collected, processed, unprocessed) values (33, 'WA', 'Seattle', 106, 462, 406);
insert into accountability (accountability_id, state, city, collected, processed, unprocessed) values (34, 'CA', 'Inglewood', 296, 78, 326);
insert into accountability (accountability_id, state, city, collected, processed, unprocessed) values (35, 'NC', 'Fayetteville', 295, 37, 294);
insert into accountability (accountability_id, state, city, collected, processed, unprocessed) values (36, 'PA', 'Bethlehem', 116, 163, 482);
insert into accountability (accountability_id, state, city, collected, processed, unprocessed) values (37, 'DC', 'Washington', 259, 15, 143);
insert into accountability (accountability_id, state, city, collected, processed, unprocessed) values (38, 'NJ', 'Trenton', 55, 341, 148);
insert into accountability (accountability_id, state, city, collected, processed, unprocessed) values (39, 'KS', 'Wichita', 259, 192, 175);
insert into accountability (accountability_id, state, city, collected, processed, unprocessed) values (40, 'FL', 'Ocala', 313, 341, 491);
insert into accountability (accountability_id, state, city, collected, processed, unprocessed) values (41, 'CA', 'San Francisco', 71, 371, 274);
insert into accountability (accountability_id, state, city, collected, processed, unprocessed) values (42, 'CA', 'San Jose', 173, 302, 349);
insert into accountability (accountability_id, state, city, collected, processed, unprocessed) values (43, 'TX', 'Dallas', 248, 53, 339);
insert into accountability (accountability_id, state, city, collected, processed, unprocessed) values (44, 'KY', 'Migrate', 78, 479, 181);
insert into accountability (accountability_id, state, city, collected, processed, unprocessed) values (45, 'PA', 'New Castle', 474, 250, 325);
insert into accountability (accountability_id, state, city, collected, processed, unprocessed) values (46, 'CA', 'San Diego', 165, 34, 299);
insert into accountability (accountability_id, state, city, collected, processed, unprocessed) values (47, 'MD', 'Baltimore', 23, 288, 142);
insert into accountability (accountability_id, state, city, collected, processed, unprocessed) values (48, 'NY', 'Staten Island', 273, 339, 218);
insert into accountability (accountability_id, state, city, collected, processed, unprocessed) values (49, 'MS', 'Jackson', 432, 44, 161);
insert into accountability (accountability_id, state, city, collected, processed, unprocessed) values (50, 'VT', 'Montpelier', 5, 218, 344);
