insert into SAEK_submission (SAEK_submission_id, submission_datetime, processing_location, storage_location) values (1, '2017-07-05', 'Police Evidence', 'Evidence');
insert into SAEK_submission (SAEK_submission_id, submission_datetime, processing_location, storage_location) values (2, '2019-05-24', 'Police Evidence', 'Evidence');
insert into SAEK_submission (SAEK_submission_id, submission_datetime, processing_location, storage_location) values (3, '2014-09-20', 'Public Crime Lab', 'Lab');
insert into SAEK_submission (SAEK_submission_id, submission_datetime, processing_location, storage_location) values (4, '2010-09-03', 'Private Crime Lab', 'Lab');
insert into SAEK_submission (SAEK_submission_id, submission_datetime, processing_location, storage_location) values (5, '2017-04-05', 'Private Crime Lab', 'Lab');
insert into SAEK_submission (SAEK_submission_id, submission_datetime, processing_location, storage_location) values (6, '2017-09-01', 'Police Evidence', 'Evidence');
insert into SAEK_submission (SAEK_submission_id, submission_datetime, processing_location, storage_location) values (7, '2020-05-30', 'Public Crime Lab', 'Lab');
insert into SAEK_submission (SAEK_submission_id, submission_datetime, processing_location, storage_location) values (8, '2012-07-04', 'Public Crime Lab', 'Clinic');
insert into SAEK_submission (SAEK_submission_id, submission_datetime, processing_location, storage_location) values (9, '2010-07-28', 'Private Crime Lab', 'Clinic');
insert into SAEK_submission (SAEK_submission_id, submission_datetime, processing_location, storage_location) values (10, '2011-07-12', 'Private Crime Lab', 'Clinic');
insert into SAEK_submission (SAEK_submission_id, submission_datetime, processing_location, storage_location) values (11, '2016-02-11', 'Police Evidence', 'Evidence');
insert into SAEK_submission (SAEK_submission_id, submission_datetime, processing_location, storage_location) values (12, '2012-04-08', 'Police Evidence', 'Evidence');
insert into SAEK_submission (SAEK_submission_id, submission_datetime, processing_location, storage_location) values (13, '2014-09-03', 'Police Evidence', 'Evidence');
insert into SAEK_submission (SAEK_submission_id, submission_datetime, processing_location, storage_location) values (14, '2012-10-29', 'Public Crime Lab', 'Lab');
insert into SAEK_submission (SAEK_submission_id, submission_datetime, processing_location, storage_location) values (15, '2015-09-04', 'Public Crime Lab', 'Lab');
