insert into SAFE (SAFE_id, first_name, last_name) values (1, 'Neddie', 'Matura');
insert into SAFE (SAFE_id, first_name, last_name) values (2, 'Bing', 'Van Rembrandt');
insert into SAFE (SAFE_id, first_name, last_name) values (3, 'Shellysheldon', 'O''Cullen');
insert into SAFE (SAFE_id, first_name, last_name) values (4, 'Nico', 'Cajkler');
insert into SAFE (SAFE_id, first_name, last_name) values (5, 'Tonya', 'Molesworth');
insert into SAFE (SAFE_id, first_name, last_name) values (6, 'Chico', 'Morey');
insert into SAFE (SAFE_id, first_name, last_name) values (7, 'Trude', 'Pemberton');
insert into SAFE (SAFE_id, first_name, last_name) values (8, 'Patricio', 'Plant');
insert into SAFE (SAFE_id, first_name, last_name) values (9, 'Alethea', 'Blasetti');
insert into SAFE (SAFE_id, first_name, last_name) values (10, 'York', 'Jelliman');
insert into SAFE (SAFE_id, first_name, last_name) values (11, 'Cy', 'Bittlestone');
insert into SAFE (SAFE_id, first_name, last_name) values (12, 'Mala', 'Gonnelly');
insert into SAFE (SAFE_id, first_name, last_name) values (13, 'Vail', 'Thornebarrow');
